### ISSUE TITLE
side-bar for menu

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#1]
As a user, I need to be able to select a different set of options from the menu so I can navigate to different app functionalities such as:
- Time Clock
- Time Entries
- Reports

Acceptance Criteria
- The UI must show the above-mentioned options and these options should be visible all the time, no matter what option have been selected
- After clicking on each option a different page containing a message should be displayed in the workplace (center of the screen), for example: 

   - Time Clock -> You clicked on Time Clock
   - Time Entries -> You clicked on Time Entries
   - Reports -> You clicked on Reports

- The selected option should have a different background-color indicating the option is currently active
- All the code should have at least 80% of code coverage

**Comment by daros10** [comment]
![sidebar](https://user-images.githubusercontent.com/20827445/76808780-cda3e300-67b6-11ea-9cf3-fa6684ccb133.png)

![coverage](https://user-images.githubusercontent.com/20827445/76808573-2de65500-67b6-11ea-9d1d-3dc787b95a2e.png)
