### ISSUE TITLE
Filter projects and project types by customer

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#154]
As a user, I want to see only the project types and projects that belong to the customer I am working with in order to avoid having confusion.

Please use the endpoints implemented in the ticket https://github.com/ioet/time-tracker-backend/issues/93 to make this work.

**Comment by EliuX** [comment]
Instead of https://github.com/ioet/time-tracker-backend/issues/93 you should guide yourselves by  https://github.com/ioet/time-tracker-backend/issues/91
