### ISSUE TITLE
change application colors

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#19]
ioet has its own set of colors and the current app is using a plain black-white-gray color combination.

Let's update the application look and feel using the colors that ioet has. In order to have an idea please check the image below:

![image](https://user-images.githubusercontent.com/1638636/77018298-ff4db300-694a-11ea-9e67-7e5497c73d22.png)

Acceptance Criteria
- Colors are updated in the app using the colors from the attached image
- Update nav-bar, menu and the other components used
- Update the README file with any required instruction if it's needed to create new components

**Comment by ralden** [comment]
Here is the official color spec:

[Ioet pantones 1.1.pdf](https://github.com/ioet/time-tracker-ui/files/4355374/Ioet.pantones.1.1.pdf)

**Comment by ralden** [comment]
logo without ioet:

![slack icon Recurso 9@6x](https://user-images.githubusercontent.com/10171462/77083966-876ba100-69bb-11ea-8249-b78206d62a71.png)

Horizontal logo:

![Recurso 6@6x](https://user-images.githubusercontent.com/10171462/77083887-6c992c80-69bb-11ea-90b3-a2c8a301c11d.png)
