### ISSUE TITLE
apply pipe on entry list

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#225]
Refactor entry list removing cards by table
Remove moment from controller to calculate time and use the implemented substractPipe
Remove icon from create-new-entry button
Remove non-needed styles
Remove project id from the table
Include ticket uri on the table

**Comment by ralden** [comment]
What is a "pipe"?

**Comment by enriquezrene** [comment]
https://angular.io/guide/pipes @ralden
