### ISSUE TITLE
Implement a CI 

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#25]
Please write a yml file with the required instructions to deploy this app on Azure using AzurePipelines

**Acceptance Criteria**
- A yml file with the pipeline definition should be created and placed on the project root
- Update the README file with any required instruction
- Make sure the pipeline is execute after merging a branch against master

**Comment by enriquezrene** [comment]
@macrisguncay 
This is already implemented, right?

**Comment by macrisguncay** [comment]
Yes, this ticket is already implemented, I was waiting for the approbation of changes in readme file. (This ticket was solved with GitHub Actions).

**Comment by enriquezrene** [comment]
PR has been approved and merged
