### ISSUE TITLE
use tags as technology names for time-entries

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#29]
As a user, I need to specify the technologies I am working with so people can use this data later to know the technologies I know about.

**Acceptance Criteria**
- The screen to create time-entries should use StackExchange API to read all the available technologies in well-known platforms like StackOverflow. The following request will return coincidences for technologies with the "java" as part of their names

**Request**
`GET https://api.stackexchange.com/2.2/tags?order=desc&sort=popular&inname=java&site=stackoverflow`

**Response**
`{"items":[{"has_synonyms":true,"is_moderator_only":false,"is_required":false,"count":1966738,"name":"javascript"},{"has_synonyms":true,"is_moderator_only":false,"is_required":false,"count":1648416,"name":"java"},...`

- The technology field should list all the coincidences provided by the above-mentioned API
- All code needs to have tests
- A new API Key should be requested and stored in Azure Key Vault

**Comment by enriquezrene** [comment]
More information available here https://api.stackexchange.com/docs/tags

**Comment by ralden** [comment]
Now this is a good idea!
