### ISSUE TITLE
Allow editing entries when they are in clock-in state

### ISSUE THREAD

**Issue by Yaneida** [ioet/time-tracker-ui#326]
Currently, after trying to edit an entry that is still opened and clicking on the save button, there is a message  "You must end the time entry before start it" and, it doesn't allow you to update the entry.

Task
Even though the entry is still opened, the user should be able to edit it.

**Comment by enriquezrene** [comment]
It's because of the end_time @Yaneida . You should set a value in there. Otherwise, you will try to set a end_time before the start time the entry has.
