### ISSUE TITLE
set seconds to 00

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#399]
When a new entry is created from the time-entries menu option we need to set the start_times with seconds 00 and the same for end time.

When a user clock-in we need to set the current time with 00 seconds as well, and when the user clocks out we need to do the same.

You need to visit the functionalities in:
- time-entries.component.ts => doSave(entry) function
- project-list-hover.component.ts => clockIn(selectedProject, customerName, name) function
- project-list-hover.component.ts => switch(selectedProject, customerName, name) function
- time-clock.component.ts =>  clockOut() funcion

Make sure the backend allows saving this info, for example an entry:

start time => 18-06-2020T10:00:00Z
**end time => 18-06-2020T11:00:00Z**

**start time => 18-06-2020T11:00:00Z**
end time => 18-06-2020T15:00:00Z

Notice that both entries have the same value for end_time and start_time

**Comment by Angeluz-07** [comment]
After discussion, it has been decided:
```
Clock-in / Clock-out y Switch quedan igual.
Si creo un nuevo time-entry desde la opcion time-entries, entonces:
time in -> tiene por defecto la ingresada por el usuario + 01 segundo
time out -> tiene por defecto la ingresada por el usuario + 00 segundos
Si el usuario edita un time entry, pero no edita ni el time in ni el time out dejo esos campos iguales.
Si el usuario edita un time entry, y cambia en time-in, por defecto dicho time-in tendra 01 segundo.
Si el usuario edita un time entry, y cambia el time out, por defecto dicho time-out tendra 00 segundos.
```
