### ISSUE TITLE
Time clock- Clock in

### ISSUE THREAD

**Issue by caruizv** [ioet/time-tracker-ui#4]
As a user I need to be able to clock in and fill out all the details (Activity, Jira ticket, Technology, and Notes) after selecting a project.

Acceptance criteria:

- When mouse over a project, a clock-in button should appear next to the project name.
- When the clock in button is clicked, show the above mentioned detail fields 
- Project name color-background should change when selected
- Clock out button should be visible after clock in .
- All the code should have at least 80% test coverage

The following fields should be marked as required: Activity and Technology

**Comment by daros10** [comment]
The team discussed this UI and we decided to apply the changes. You can see the result in the attached file.

![1](https://user-images.githubusercontent.com/20827445/76815578-ff737480-67cb-11ea-9264-3a2350947898.png)

![2](https://user-images.githubusercontent.com/20827445/76815580-000c0b00-67cc-11ea-8ed4-6544278fa812.png)
