### ISSUE TITLE
Fix/improve reports table

### ISSUE THREAD

**Issue by astridschneider** [ioet/time-tracker-ui#418]
![Screen Shot 2020-06-23 at 3 35 04 PM](https://user-images.githubusercontent.com/31556785/85458879-31cd0480-b567-11ea-99e2-4df257d0631d.png)
- header doesn't always fit the table
- make font size smaller
- change first column to "user" and remove @ioet.com from user names.

**Comment by enriquezrene** [comment]
Ignore the last point from the Acceptance Criteria
