### ISSUE TITLE
Increase height for technologies component

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#461]
Increase height for technologies component, please refer to https://ioetec.slack.com/archives/C01694949JR/p1593710964016500

We can also display a vertical scroll that users can click and navigate through the results.

**Comment by Angeluz-07** [comment]
I could increase the height of the div where technologies are listed to show initial 5 items completely. However this component is not based in the <select> html element, and couldn't avoid to partially hide a technology name when scrolling down/up.

To control this. I looked for some solutions similar to [this](http://lab.stephaneguigne.com/js/jquery-scrollsections/example/callbacks.html). But required some Jquery dependencies.

At the end, I decided to use [scroll-snap styles](https://24ways.org/2019/beautiful-scrolling-experiences-without-libraries/) as a simpler solution with almost the same effect.
