### ISSUE TITLE
Pre-load data on switching between projects

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-ui#503]
As a user, I want to see the data of my last entry saved in the application when I am switching from one project to other.

**Acceptance Criteria**

- In the time-clock page, when a user switch from one project to other, the last entry created for the new project selected should be loaded and the fields should be populated in the screen

**Note**
The application is already doing this when the user clicks on `Clock in`, we need to replicate the same behavior for `Switch`

**Comment by Angeluz-07** [comment]
Very useful description.
